In [27]:
import matplotlib.pyplot as plt
import pandas as pd
# create Dataframes using CSV file
df=pd.read_csv('housing.csv')
df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  int64  
 3   total_rooms         20640 non-null  int64  
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  int64  
 6   households          20640 non-null  int64  
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  int64  
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(4), int64(5), object(1)
memory usage: 1.6+ MB


longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000   
mean    -119.569704     35.631861           28.639486   2635.763081   
std        2.003532      2.135952           12.585558   2181.615252   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1447.750000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.710000           37.000000   3148.000000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  \
count    20433.000000  20640.000000  20640.000000   20640.000000   
mean       537.870553   1425.476744    499.539680       3.870671   
std        421.385070   1132.462122    382.329753       1.899822   
min          1.000000      3.000000      1.000000       0.499900   
25%        296.000000    787.000000    280.000000       2.563400   
50%        435.000000   1166.000000    409.000000       3.534800   
75%        647.000000   1725.000000    605.000000       4.743250   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        20640.000000  
mean        206855.816909  
std         115395.615874  
min          14999.000000  
25%         119600.000000  
50%         179700.000000  
75%         264725.000000  
max         500001.000000

In [28]:
from sklearn.model_selection import train_test_split
df.dropna(inplace=True)
train_set, test_set= train_test_split(df,test_size=0.2,random_state=50)
x_train=train_set.iloc[:,:-2]
x_train

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
11084    -122.17     38.07                  15         2125           278.0   
19184    -121.76     37.26                  17          250            52.0   
19106    -117.69     33.58                   5         6678          1011.0   
6664     -118.09     34.07                  31         1054           252.0   
7474     -122.04     37.97                  21         6445          1839.0   
...          ...       ...                 ...          ...             ...   
14715    -118.29     34.07                  26         2302          1124.0   
15815    -120.87     37.77                   9         4838           920.0   
10228    -120.33     34.87                  24         2590           404.0   
5653     -122.81     38.46                  28         3580           611.0   
14145    -117.79     35.21                   4            2             2.0   

       population  households  median_income  
11084         857         272         6.4599  
19184         141          51         4.6458  
19106        2877         982         7.5177  
6664         1032         258         2.3424  
7474         3621        1735         2.5841  
...           ...         ...            ...  
14715        2660        1004         2.3567  
15815        2460         923         3.5959  
10228        1093         338         3.9375  
5653         1634         567         4.7450  
14145           6           2         2.3750  

[16346 rows x 8 columns]

In [29]:
y1_train=train_set.iloc[:,-2:]
y1_train

median_house_value ocean_proximity
11084              219700        NEAR BAY
19184              500001       <1H OCEAN
19106              330000       <1H OCEAN
6664               188500       <1H OCEAN
7474               112500        NEAR BAY
...                   ...             ...
14715              253100       <1H OCEAN
15815              142700          INLAND
10228              341200       <1H OCEAN
5653               248600       <1H OCEAN
14145              137500          INLAND

[16346 rows x 2 columns]

In [30]:
y_train= y1_train.iloc[:,:1]
y_train
x_test = test_set.iloc[:,:-2]
x_test
y1_test = test_set.iloc[:,-2:]
y1_test
y_test = y1_test.iloc[:,:1]
y_test



median_house_value
17513              110900
6777               291100
15327              249400
11212              425000
581                268500
...                   ...
19434              341300
7851               173700
12271               90400
10466              230600
16019              226400

[4087 rows x 1 columns]

In [31]:
#training model 1
from sklearn.linear_model import LinearRegression
model1= LinearRegression()
model1.fit(x_train,y_train)

LinearRegression()

In [32]:
#Testing Model
y_pred = model1.predict(x_test)
print(y_pred)

[[ 66990.29013307]
 [306517.55147855]
 [283917.28620756]
 ...
 [143515.36476237]
 [286578.5819223 ]
 [237197.25277824]]


In [33]:
# Mean Squared Error
from sklearn.metrics import mean_squared_error
rmse = mean_squared_error(y_pred,y_test,squared = False)
rmse

69562.84661587632

In [34]:
x_sample = [[-122.23,37.88,41,880,129.0,322,126,8.3252]]
y_pred = model1.predict(x_sample)
print(y_pred)

[[410538.44765994]]


C:\Users\MTCS32\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [35]:
#training 2
from sklearn.tree import DecisionTreeRegressor
model2= DecisionTreeRegressor()
model2.fit(x_train,y_train)

DecisionTreeRegressor()

In [39]:
#Testing Model
y_pred = model2.predict(x_test)
print(y_pred)

[124800. 289100. 235800. ... 101200. 202700. 259800.]


In [41]:
# Mean Squared Error
from sklearn.metrics import mean_squared_error
rmse = mean_squared_error(y_pred,y_test,squared = False)
rmse

66927.75333132155

In [46]:
#Using Cross Validation
from sklearn.model_selection import cross_val_score
model2_rmse= -cross_val_score(model2,x_train,y_train,scoring="neg_root_mean_squared_error",cv=10)
print(model2_rmse)
pd.Series(model2_rmse).describe()

[69880.15134301 73101.99039729 70338.5433695  75200.12740927
 68278.65105499 69650.03323823 72976.40345094 70687.24818167
 72316.73328926 71613.69665784]


count       10.000000
mean     71404.357839
std       2040.111978
min      68278.651055
25%      69994.749350
50%      71150.472420
75%      72811.485911
max      75200.127409
dtype: float64

In [54]:
#training 3
import numpy as np
from sklearn.ensemble import RandomForestRegressor
model3= RandomForestRegressor()
model3.fit(x_train,np.ravel(y_train))

RandomForestRegressor()

In [55]:
#Testing Model
y_pred = model3.predict(x_test)
print(y_pred)

[157970.   292393.03 279639.04 ... 107937.   256395.01 290376.14]


In [56]:
#Using Cross Validation
from sklearn.model_selection import cross_val_score
model3_rmse= -cross_val_score(model3,x_train,y_train,scoring="neg_root_mean_squared_error",cv=10)
print(model3_rmse)
pd.Series(model3_rmse).describe()

C:\Users\MTCS32\anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\MTCS32\anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\MTCS32\anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\MTCS32\anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,),

[47082.23317099 50392.31880906 48238.65943136 51908.1283753
 50098.67204731 49816.17179013 51361.74128183 50381.49812948
 51102.9678683  47532.34407061]


count       10.000000
mean     49791.473497
std       1644.012430
min      47082.233171
25%      48633.037521
50%      50240.085088
75%      50925.305603
max      51908.128375
dtype: float64